name: escape_markup
description: Escape a string for use in HTML or the inverse.
version: 1.0.0-dev.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
